# Generated by Django 6.0 on 2026-03-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="amount_paid",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="The amount actually charged at the time of payment. Set by the payment webhook.",
                max_digits=10,
                null=True,
            ),
        ),
    ]
