# Generated by Django 6.0 on 2026-03-16 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_alter_motorcycle_is_featured"),
        ("payments", "0003_order_amount_paid"),
        ("product", "0003_product_is_featured"),
    ]

    operations = [
        migrations.CreateModel(
            name="DepositSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deposit_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=550.0,
                        help_text="Flat deposit amount charged when a customer reserves a motorcycle (AUD).",
                        max_digits=10,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Deposit Settings",
                "verbose_name_plural": "Deposit Settings",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="motorcycle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="inventory.motorcycle",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_type",
            field=models.CharField(
                choices=[("full", "Full Payment"), ("deposit", "Deposit")],
                default="full",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="product.product",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_payment", "Pending Payment"),
                    ("paid", "Paid"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("refunded", "Refunded"),
                ],
                default="pending_payment",
                max_length=20,
            ),
        ),
    ]
