# Generated by Django 6.0 on 2026-03-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "payments",
            "0004_depositsettings_order_motorcycle_order_payment_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="address_line1",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="order",
            name="postcode",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="order",
            name="state",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="order",
            name="suburb",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
