# Generated by Django 6.0 on 2026-03-28 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hire", "0002_remove_hiresettings_enable_hire"),
        ("payments", "0005_alter_order_address_line1_alter_order_postcode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="hire_booking",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment",
                to="hire.hirebooking",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="order",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment",
                to="payments.order",
            ),
        ),
    ]
