# Generated by Django 6.0 on 2026-03-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0006_payment_hire_booking_alter_payment_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="terms_accepted",
            field=models.BooleanField(
                default=False,
                help_text="Customer accepted terms and conditions at order time.",
            ),
        ),
    ]
