# Generated by Django 6.0 on 2026-07-24 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parts", "0003_partsorder_partsorderitem"),
        ("payments", "0008_order_selected_colour"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="parts_order",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment",
                to="parts.partsorder",
            ),
        ),
    ]
