# Generated by Django 6.0 on 2026-07-29 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0020_bikeorder"),
        ("payments", "0009_payment_parts_order"),
        ("product", "0007_productorder"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="bike_order",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment",
                to="inventory.bikeorder",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="product_order",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment",
                to="product.productorder",
            ),
        ),
    ]
