# Generated by Django 6.0 on 2026-07-29 10:31

from django.db import migrations, models


def validate_payment_targets(apps, schema_editor):
    Payment = apps.get_model("payments", "Payment")
    invalid_ids = []
    for payment in Payment.objects.only(
        "pk", "product_order_id", "bike_order_id", "hire_booking_id", "parts_order_id"
    ).iterator():
        target_count = sum(
            target_id is not None
            for target_id in (
                payment.product_order_id,
                payment.bike_order_id,
                payment.hire_booking_id,
                payment.parts_order_id,
            )
        )
        if target_count != 1:
            invalid_ids.append(payment.pk)

    if invalid_ids:
        sample = ", ".join(str(pk) for pk in invalid_ids[:10])
        raise RuntimeError(
            "Cannot enforce payment target integrity: "
            f"{len(invalid_ids)} payment row(s) do not have exactly one target "
            f"(sample ids: {sample})."
        )


class Migration(migrations.Migration):

    dependencies = [
        ("hire", "0009_hiresettings_monthly_discount_percent_and_more"),
        ("inventory", "0020_bikeorder"),
        ("parts", "0002_partsorderitem_markup_percentage_and_more"),
        ("payments", "0011_split_legacy_orders"),
        ("product", "0007_productorder"),
    ]

    operations = [
        # Run every data-integrity gate before schema changes. MySQL DDL is not
        # transactional, so a failure after RemoveField would leave a partially
        # applied migration even though Django does not record it as applied.
        migrations.RunPython(validate_payment_targets, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="order",
            name="motorcycle",
        ),
        migrations.RemoveField(
            model_name="order",
            name="product",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="order",
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("bike_order__isnull", True),
                        ("hire_booking__isnull", True),
                        ("parts_order__isnull", True),
                        ("product_order__isnull", False),
                    ),
                    models.Q(
                        ("bike_order__isnull", False),
                        ("hire_booking__isnull", True),
                        ("parts_order__isnull", True),
                        ("product_order__isnull", True),
                    ),
                    models.Q(
                        ("bike_order__isnull", True),
                        ("hire_booking__isnull", False),
                        ("parts_order__isnull", True),
                        ("product_order__isnull", True),
                    ),
                    models.Q(
                        ("bike_order__isnull", True),
                        ("hire_booking__isnull", True),
                        ("parts_order__isnull", False),
                        ("product_order__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="payment_exactly_one_target",
            ),
        ),
        migrations.DeleteModel(
            name="Order",
        ),
    ]
