# Generated by Django 6.0 on 2026-07-29 12:04

import django.db.models.deletion
from django.db import migrations, models


def delete_orphaned_payment_attempts(apps, schema_editor):
    """Remove legacy/test attempts whose target row no longer exists."""
    Payment = apps.get_model("payments", "Payment")
    targets = (
        ("product_order_id", apps.get_model("product", "ProductOrder")),
        ("bike_order_id", apps.get_model("inventory", "BikeOrder")),
        ("hire_booking_id", apps.get_model("hire", "HireBooking")),
        ("parts_order_id", apps.get_model("parts", "PartsOrder")),
    )
    for field_name, target_model in targets:
        Payment.objects.filter(**{f"{field_name}__isnull": False}).exclude(
            **{f"{field_name}__in": target_model.objects.values("pk")}
        ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("hire", "0010_hirebooking_access_token"),
        ("inventory", "0020_bikeorder"),
        ("parts", "0002_partsorderitem_markup_percentage_and_more"),
        ("payments", "0012_remove_order_motorcycle_remove_order_product_and_more"),
        ("product", "0007_productorder"),
    ]

    operations = [
        migrations.RunPython(delete_orphaned_payment_attempts, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="payment",
            name="bike_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="inventory.bikeorder",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="hire_booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="hire.hirebooking",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="parts_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="parts.partsorder",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="product_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="product.productorder",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("succeeded", "Succeeded"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
