# Generated by Django 6.0 on 2026-03-28 12:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_management", "0005_delete_brand"),
    ]

    operations = [
        # Clear existing records — the terms system is being replaced with a per-type model.
        # New records will be loaded via `python manage.py generate --terms`.
        migrations.RunSQL(
            "DELETE FROM data_management_termsandconditions;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddField(
            model_name="termsandconditions",
            name="term_type",
            field=models.CharField(
                choices=[
                    ("hire", "Hire"),
                    ("service", "Service"),
                    ("purchase", "Purchase"),
                ],
                default="purchase",
                help_text="The type of terms (hire, service, purchase).",
                max_length=20,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="termsandconditions",
            name="published_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="The date and time these terms were last published.",
            ),
        ),
        migrations.AlterField(
            model_name="termsandconditions",
            name="version",
            field=models.CharField(
                blank=True,
                help_text="Optional version label, e.g. '2026-03'.",
                max_length=20,
            ),
        ),
    ]
