# Generated by Django 6.0 on 2026-03-28 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_management", "0006_termsandconditions_term_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="termsandconditions",
            name="version",
        ),
    ]
