# Generated by Django 6.0 on 2026-03-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Optional discounted GST-inclusive price in AUD.",
                max_digits=10,
                null=True,
            ),
        ),
    ]
