# Generated by Django 6.0 on 2026-03-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_product_youtube_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="youtube_link",
            field=models.URLField(
                blank=True,
                help_text="An optional link to a YouTube video for this product.",
                max_length=255,
                null=True,
            ),
        ),
    ]
