# Generated by Django 6.0 on 2026-03-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_alter_product_youtube_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="popular",
            field=models.BooleanField(
                default=False,
                help_text="Popular products are highlighted in the listing page.",
            ),
        ),
    ]
