# Generated by Django 6.0 on 2026-07-29 10:22

import django.db.models.deletion
import product.models.product_order
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_product_popular"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_reference",
                    models.CharField(blank=True, max_length=20, unique=True),
                ),
                (
                    "access_token",
                    models.CharField(
                        default=product.models.product_order._generate_access_token,
                        editable=False,
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("customer_name", models.CharField(max_length=200)),
                ("customer_email", models.EmailField(max_length=254)),
                ("customer_phone", models.CharField(blank=True, max_length=50)),
                ("address_line1", models.CharField(max_length=200)),
                ("address_line2", models.CharField(blank=True, max_length=200)),
                ("suburb", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=3)),
                ("postcode", models.CharField(max_length=4)),
                ("country", models.CharField(default="Australia", max_length=100)),
                (
                    "unit_price_incl_gst",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Effective product price snapshotted when the order was created.",
                        max_digits=10,
                    ),
                ),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "amount_paid",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_payment", "Pending Payment"),
                            ("paid", "Paid"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending_payment",
                        max_length=20,
                    ),
                ),
                ("terms_accepted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_orders",
                        to="product.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
