# Generated by Django 6.0 on 2026-01-02 14:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255, unique=True)),
                ("answer", models.TextField()),
                (
                    "pages",
                    models.JSONField(
                        default=list,
                        help_text='A list of page identifiers where this FAQ should appear (e.g., ["home", "substitutes"])',
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "FAQs",
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enable_motorcycle_mover",
                    models.BooleanField(
                        default=True, help_text="Enable the motorcycle mover section."
                    ),
                ),
                (
                    "enable_banner",
                    models.BooleanField(
                        default=False,
                        help_text="Enable a site-wide announcement banner.",
                    ),
                ),
                (
                    "banner_text",
                    models.CharField(
                        blank=True,
                        default="Formerly known as Scootershop Fremantle. Same expert, new location!",
                        help_text="The text to display in the banner.",
                        max_length=255,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        default="94334613",
                        help_text="shop phone",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "email_address",
                    models.EmailField(
                        blank=True,
                        default="admin@scootershop.com.au",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "street_address",
                    models.CharField(
                        blank=True,
                        default="Unit 5 / 6 Cleveland Street",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "address_locality",
                    models.CharField(
                        blank=True, default="Dianella", max_length=100, null=True
                    ),
                ),
                (
                    "address_region",
                    models.CharField(
                        blank=True, default="WA", max_length=100, null=True
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, default="6059", max_length=20, null=True
                    ),
                ),
                (
                    "google_places_place_id",
                    models.CharField(
                        blank=True,
                        default="ChIJy_zrHmGhMioRisz6mis0SpQ",
                        help_text="Google Places Place ID for the storefront location",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "mrb_number",
                    models.CharField(
                        blank=True,
                        default="MRB5092",
                        help_text="Motor Vehicle Repairer's Business number.",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "abn_number",
                    models.CharField(
                        blank=True,
                        default="46157594161",
                        help_text="Australian Business Number.",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "md_number",
                    models.CharField(
                        blank=True,
                        default="28276",
                        help_text="Motor Dealer's number.",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "youtube_link",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "instagram_link",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "facebook_link",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "opening_hours_monday",
                    models.CharField(
                        blank=True,
                        default="9:00 AM - 5:00 PM",
                        help_text="e.g. '9:00 AM - 5:00 PM' or 'Closed'",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "opening_hours_tuesday",
                    models.CharField(
                        blank=True,
                        default="9:00 AM - 5:00 PM",
                        help_text="e.g. '9:00 AM - 5:00 PM' or 'Closed'",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "opening_hours_wednesday",
                    models.CharField(
                        blank=True,
                        default="9:00 AM - 5:00 PM",
                        help_text="e.g. '9:00 AM - 5:00 PM' or 'Closed'",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "opening_hours_thursday",
                    models.CharField(
                        blank=True,
                        default="9:00 AM - 5:00 PM",
                        help_text="e.g. '9:00 AM - 5:00 PM' or 'Closed'",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "opening_hours_friday",
                    models.CharField(
                        blank=True,
                        default="9:00 AM - 5:00 PM",
                        help_text="e.g. '9:00 AM - 5:00 PM' or 'Closed'",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "opening_hours_saturday",
                    models.CharField(
                        blank=True,
                        default="Closed",
                        help_text="e.g. '9:00 AM - 5:00 PM' or 'Closed'",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "opening_hours_sunday",
                    models.CharField(
                        blank=True,
                        default="Closed",
                        help_text="e.g. '9:00 AM - 5:00 PM' or 'Closed'",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="TermsAndConditions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        help_text="Version number, e.g., '1.0'",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="The full HTML content of the terms and conditions."
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="The date and time this version was published.",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Terms and Conditions",
                "ordering": ["-published_at"],
            },
        ),
    ]
