# Generated by Django 6.0 on 2026-01-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="mobile_number",
            field=models.CharField(
                blank=True, help_text="shop mobile number", max_length=20, null=True
            ),
        ),
    ]
