# Generated by Django 6.0 on 2026-01-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_management", "0002_alter_sitesettings_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("serviceable", models.BooleanField(default=False)),
            ],
        ),
    ]
