# Generated by Django 6.0 on 2026-01-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_management", "0002_sitesettings_mobile_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="mobile_number",
            field=models.CharField(
                blank=True,
                default="0477700005",
                help_text="mobile number",
                max_length=20,
                null=True,
            ),
        ),
    ]
