# Generated by Django 6.0 on 2026-01-08 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_management", "0003_alter_sitesettings_mobile_number"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SiteSettings",
        ),
    ]
