# Generated by Django 6.0 on 2026-01-05 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_management", "0003_brand"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FAQ",
        ),
    ]
