# Generated by Django 6.0 on 2026-03-12 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_management", "0004_delete_sitesettings"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Brand",
        ),
    ]
