# Generated by Django 6.0 on 2026-07-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_management", "0007_remove_termsandconditions_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="termsandconditions",
            name="term_type",
            field=models.CharField(
                choices=[
                    ("hire", "Hire"),
                    ("service", "Service"),
                    ("purchase", "Purchase"),
                    ("parts", "New SYM Parts"),
                ],
                default="purchase",
                help_text="The type of terms (hire, service, purchase, parts).",
                max_length=20,
                unique=True,
            ),
        ),
    ]
