# Generated by Django 6.0 on 2026-07-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="partsorderitem",
            name="markup_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Parts Settings markup snapshotted at checkout.",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="partsorderitem",
            name="rrp_unit_price_incl_gst",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="RRP+GST from the supplier feed at checkout.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="partsorderitem",
            name="supplier_discount_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Configured supplier discount snapshotted at checkout.",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="partsorderitem",
            name="supplier_unit_cost_incl_gst",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Actual discounted unit cost including GST at checkout.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="wholesale_price_incl_gst",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="RRP including GST from the PA 'RRP+GST' column; null = unknown.",
                max_digits=10,
                null=True,
            ),
        ),
    ]
