# Generated by Django 6.0 on 2026-07-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sectionpart",
            name="superseded_flag",
            field=models.CharField(
                blank=True,
                help_text="The book's supersession flag/note (usually Y/N).",
                max_length=50,
            ),
        ),
    ]
