# Generated by Django 6.0 on 2026-07-27 11:44

import django.db.models.deletion
import parts.models.parts_order
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parts", "0002_alter_sectionpart_superseded_flag"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartsOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_reference",
                    models.CharField(blank=True, max_length=20, unique=True),
                ),
                (
                    "access_token",
                    models.CharField(
                        default=parts.models.parts_order._generate_access_token,
                        editable=False,
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("customer_name", models.CharField(max_length=200)),
                ("customer_email", models.EmailField(max_length=254)),
                ("customer_phone", models.CharField(blank=True, max_length=50)),
                ("address_line1", models.CharField(max_length=200)),
                ("address_line2", models.CharField(blank=True, max_length=200)),
                ("suburb", models.CharField(max_length=100)),
                ("state", models.CharField(blank=True, max_length=50)),
                ("postcode", models.CharField(max_length=20)),
                ("country", models.CharField(default="Australia", max_length=100)),
                (
                    "is_international",
                    models.BooleanField(
                        default=False,
                        help_text="Derived from country at order time; drives shipping fee.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_payment", "Pending Payment"),
                            ("paid", "Paid"),
                            ("dispatched", "Dispatched"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                            ("partially_refunded", "Partially Refunded"),
                        ],
                        default="pending_payment",
                        max_length=20,
                    ),
                ),
                (
                    "has_backorder",
                    models.BooleanField(
                        default=False,
                        help_text="True if any line was understocked at order time.",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "shipping",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("terms_accepted", models.BooleanField(default=False)),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes (wholesaler chase-ups, etc.). Not shown to the customer.",
                    ),
                ),
                ("dispatched_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="partssettings",
            name="backorder_hold_days",
            field=models.PositiveIntegerField(
                default=7,
                help_text="Days an order can wait for a backordered part before the operator refunds it.",
            ),
        ),
        migrations.AddField(
            model_name="partssettings",
            name="enable_new_part_sales",
            field=models.BooleanField(
                default=True,
                help_text="Allow customers to add genuine new SYM parts to their cart and checkout.",
            ),
        ),
        migrations.CreateModel(
            name="PartsOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "part_number",
                    models.CharField(
                        help_text="Snapshot, incl. any colour suffix.", max_length=60
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("colour_name", models.CharField(blank=True, max_length=50)),
                ("model_name", models.CharField(blank=True, max_length=200)),
                ("model_code", models.CharField(blank=True, max_length=50)),
                ("section_code", models.CharField(blank=True, max_length=10)),
                ("ref_number", models.CharField(blank=True, max_length=20)),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Customer price incl. GST (marked up).",
                        max_digits=10,
                    ),
                ),
                ("line_total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ordered", "Ordered"),
                            ("fulfilled", "Fulfilled"),
                            ("refunded", "Refunded"),
                        ],
                        default="ordered",
                        max_length=20,
                    ),
                ),
                (
                    "backordered",
                    models.BooleanField(
                        default=False,
                        help_text="Understocked at order time / placed on backorder by admin.",
                    ),
                ),
                (
                    "backorder_since",
                    models.DateField(
                        blank=True,
                        help_text="Start of the 14-day hold clock.",
                        null=True,
                    ),
                ),
                (
                    "parts_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="parts.partsorder",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
