# Generated by Django 6.0 on 2026-08-01 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parts", "0002_partsorderitem_markup_percentage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="partsmodel",
            name="confirmed_years",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated years directly evidenced for this book code, e.g. '2007, 2008, 2009'.",
                max_length=200,
            ),
        ),
    ]
