# Generated by Django 6.0 on 2026-08-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parts", "0003_partsmodel_confirmed_years"),
    ]

    operations = [
        migrations.AddField(
            model_name="partsection",
            name="curated_diagram_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="parts/curated-diagrams/"
            ),
        ),
        migrations.AddField(
            model_name="partsection",
            name="curated_source_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="partsection",
            name="diagram_source_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
