# Generated by Django 6.0 on 2026-07-27 13:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parts", "0003_partsorder_partssettings_backorder_hold_days_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="partssettings",
            name="domestic_shipping_fee",
        ),
        migrations.RemoveField(
            model_name="partssettings",
            name="international_shipping_fee",
        ),
        migrations.AddField(
            model_name="partssettings",
            name="shipping_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("15.00"),
                help_text="Flat shipping fee (AUD) for Australian delivery addresses.",
                max_digits=10,
            ),
        ),
    ]
