# Generated by Django 6.0 on 2026-07-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parts", "0003_partsorder_partsorderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="partsorder",
            name="admin_notes",
            field=models.TextField(
                blank=True,
                help_text="Internal notes (wholesaler chase-ups, etc.). Not shown to the customer.",
            ),
        ),
        migrations.AddField(
            model_name="partsorderitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("ordered", "Ordered"),
                    ("fulfilled", "Fulfilled"),
                    ("refunded", "Refunded"),
                ],
                default="ordered",
                max_length=20,
            ),
        ),
    ]
