# Generated by Django 6.0 on 2026-08-01 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parts", "0004_partsection_curated_diagram_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="partsmodel",
            name="confirmed_years",
        ),
    ]
