# Generated by Django 6.0 on 2026-01-02 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ServiceSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booking_advance_notice",
                    models.IntegerField(
                        default=2,
                        help_text="Minimum number of days notice required for a booking (e.g., 1 for next day).",
                    ),
                ),
                (
                    "drop_off_start_time",
                    models.TimeField(
                        default=datetime.time(9, 0),
                        help_text="The earliest time customers can drop off their motorcycle.",
                    ),
                ),
                (
                    "drop_off_end_time",
                    models.TimeField(
                        default=datetime.time(17, 0),
                        help_text="The latest time customers can drop off their motorcycle.",
                    ),
                ),
            ],
        ),
    ]
