# Generated by Django 6.0 on 2026-01-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingRequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(help_text="Customer's full name", max_length=255),
                ),
                (
                    "customer_email",
                    models.EmailField(
                        help_text="Customer's email address", max_length=254
                    ),
                ),
                (
                    "vehicle_registration",
                    models.CharField(
                        blank=True,
                        help_text="Vehicle registration number",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "request_payload",
                    models.JSONField(
                        help_text="The exact JSON payload sent to Mechanics Desk."
                    ),
                ),
                (
                    "response_status_code",
                    models.PositiveIntegerField(
                        help_text="The HTTP status code from the Mechanics Desk API response."
                    ),
                ),
                (
                    "response_body",
                    models.JSONField(
                        help_text="The JSON response from the Mechanics Desk API."
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the request was made."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Success", "Success"), ("Failed", "Failed")],
                        help_text="The status of the request.",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking Request Log",
                "verbose_name_plural": "Booking Request Logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
