# Generated by Django 6.0 on 2026-01-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0002_bookingrequestlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The exact name of the job type from MechanicDesk.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="A customer-facing description of what the service includes.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this job type is active and should be displayed.",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="servicesettings",
            options={
                "verbose_name": "Service Settings",
                "verbose_name_plural": "Service Settings",
            },
        ),
    ]
