# Generated by Django 6.0 on 2026-01-04 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0003_jobtype_alter_servicesettings_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobtype",
            name="is_active",
        ),
    ]
