# Generated by Django 6.0 on 2026-07-18 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0004_remove_jobtype_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockedDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.AddField(
            model_name="servicesettings",
            name="always_blocked_weekdays",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Comma-separated weekday numbers always closed (Mon=0 … Sun=6), e.g. '6' for Sundays.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="servicesettings",
            name="reminder_days_before",
            field=models.IntegerField(
                default=1,
                help_text="How many days before drop-off the reminder email is sent.",
            ),
        ),
        migrations.AddField(
            model_name="servicesettings",
            name="reminder_emails_enabled",
            field=models.BooleanField(
                default=False,
                help_text="When on, our own reminder emails are sent (in addition to MechanicDesk's, until MechanicDesk is retired). Toggle off to avoid duplicate reminders.",
            ),
        ),
        migrations.AddField(
            model_name="servicesettings",
            name="use_mechanic_desk_blocked_dates",
            field=models.BooleanField(
                default=True,
                help_text="When on, unavailable days are read from MechanicDesk. When off, they are computed from our own rules and blocked dates below.",
            ),
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "drop_off_date",
                    models.DateField(
                        help_text="The day this job sits on in the diary."
                    ),
                ),
                (
                    "drop_off_time",
                    models.TimeField(
                        blank=True,
                        help_text="Drop-off/start time. Optional.",
                        null=True,
                    ),
                ),
                ("customer_name", models.CharField(max_length=255)),
                ("customer_phone", models.CharField(blank=True, max_length=30)),
                ("customer_email", models.EmailField(blank=True, max_length=254)),
                (
                    "bike_name",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'Vespa GTS 300' or free text.",
                        max_length=255,
                    ),
                ),
                ("registration", models.CharField(blank=True, max_length=20)),
                (
                    "job_description",
                    models.TextField(blank=True, help_text="What the job involves."),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("not_started", "Not started"),
                            ("in_progress", "In progress"),
                            ("finished_paid", "Finished & paid"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("website", "Website"), ("manual", "Manually added")],
                        default="manual",
                        max_length=10,
                    ),
                ),
                (
                    "reminder_sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the reminder email was sent, if at all.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking_log",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings",
                        to="service.bookingrequestlog",
                    ),
                ),
            ],
            options={
                "ordering": ["drop_off_date", "drop_off_time", "created_at"],
            },
        ),
    ]
