# Generated by Django 6.0 on 2026-07-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "service",
            "0005_blockeddate_servicesettings_always_blocked_weekdays_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={
                "ordering": [
                    "drop_off_date",
                    models.OrderBy(models.F("drop_off_time"), nulls_last=True),
                    "created_at",
                ]
            },
        ),
    ]
