# Generated by Django 6.0 on 2026-07-18 10:38

from django.db import migrations, models


def copy_bike_name_to_make(apps, schema_editor):
    """Preserve existing free-text vehicle names by moving them into `make`."""
    Booking = apps.get_model("service", "Booking")
    for booking in Booking.objects.exclude(bike_name="").only("id", "bike_name", "make"):
        booking.make = booking.bike_name[:100]
        booking.save(update_fields=["make"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0006_alter_booking_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="make",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="booking",
            name="model",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="booking",
            name="odometer",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="booking",
            name="postcode",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="booking",
            name="street_address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="booking",
            name="suburb",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="booking",
            name="year",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.RunPython(copy_bike_name_to_make, noop_reverse),
        migrations.RemoveField(
            model_name="booking",
            name="bike_name",
        ),
    ]
