# Generated by Django 6.0 on 2026-07-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "service",
            "0007_remove_booking_bike_name_booking_make_booking_model_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="md_job_number",
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="booking",
            name="source",
            field=models.CharField(
                choices=[
                    ("website", "Website"),
                    ("manual", "Manually added"),
                    ("imported", "Imported (MechanicDesk)"),
                ],
                default="manual",
                max_length=10,
            ),
        ),
    ]
