# Generated by Django 6.0 on 2026-07-21 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0008_booking_md_job_number_alter_booking_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="blockeddate",
            name="available",
            field=models.BooleanField(
                default=False,
                help_text="When True this is a force-open override that beats the recurring rules; when False the day is force-closed.",
            ),
        ),
    ]
