# Generated by Django 6.0 on 2026-07-22 12:36

from django.db import migrations, models

# Old value -> new value. 'requested' is unchanged; 'cancelled' is new and has
# no old equivalent, so nothing maps onto it.
STATUS_RENAMES = {
    "not_started": "accepted",
    "in_progress": "started",
    "finished_paid": "finished",
}


def rename_statuses(apps, schema_editor):
    Booking = apps.get_model("service", "Booking")
    for old, new in STATUS_RENAMES.items():
        Booking.objects.filter(status=old).update(status=new)


def revert_statuses(apps, schema_editor):
    Booking = apps.get_model("service", "Booking")
    for old, new in STATUS_RENAMES.items():
        Booking.objects.filter(status=new).update(status=old)
    # 'cancelled' has no pre-rename equivalent; park it on the closest one.
    Booking.objects.filter(status="cancelled").update(status="not_started")


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0009_blockeddate_available"),
    ]

    operations = [
        migrations.RunPython(rename_statuses, revert_statuses),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("requested", "Requested"),
                    ("accepted", "Accepted"),
                    ("started", "Started"),
                    ("finished", "Finished"),
                    ("cancelled", "Cancelled"),
                ],
                default="accepted",
                max_length=20,
            ),
        ),
    ]
