# Generated by Django 6.0 on 2026-07-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0010_alter_booking_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="state",
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
