# Generated by Django 6.0 on 2026-01-02 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MotorcycleCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
                ("display_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Motorcycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("make", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("year", models.IntegerField(blank=True, null=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Sale price (if applicable)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        blank=True,
                        choices=[("new", "New"), ("used", "Used"), ("demo", "Demo")],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("for_sale", "For Sale"),
                            ("sold", "Sold"),
                            ("reserved", "Reserved"),
                            ("unavailable", "Unavailable"),
                        ],
                        default="for_sale",
                        help_text="The sales status of the motorcycle.",
                        max_length=20,
                    ),
                ),
                ("odometer", models.IntegerField(default=0)),
                (
                    "engine_size",
                    models.IntegerField(
                        blank=True,
                        help_text="Engine size in cubic centimeters (cc)",
                        null=True,
                    ),
                ),
                (
                    "range",
                    models.IntegerField(
                        blank=True,
                        help_text="Range in kilometers (if applicable)",
                        null=True,
                    ),
                ),
                (
                    "seats",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of seats on the motorcycle",
                        null=True,
                    ),
                ),
                (
                    "transmission",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("automatic", "Automatic"),
                            ("manual", "Manual"),
                            ("semi-auto", "Semi-Automatic"),
                        ],
                        help_text="Motorcycle transmission type",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "youtube_link",
                    models.URLField(
                        blank=True,
                        help_text="An optional link to a YouTube video for this motorcycle.",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("date_posted", models.DateTimeField(auto_now_add=True)),
                (
                    "rego",
                    models.CharField(
                        blank=True,
                        help_text="Registration number",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "rego_exp",
                    models.DateField(
                        blank=True, help_text="Registration expiration date", null=True
                    ),
                ),
                (
                    "stock_number",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "warranty_months",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of months the warranty is valid for",
                        null=True,
                    ),
                ),
                (
                    "conditions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Select all applicable conditions (e.g., Used, New, Demo.)",
                        related_name="motorcycles",
                        to="inventory.motorcyclecondition",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MotorcycleImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.FileField(upload_to="motorcycles/additional/")),
                (
                    "motorcycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="inventory.motorcycle",
                    ),
                ),
            ],
        ),
    ]
