# Generated by Django 6.0 on 2026-01-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="motorcycle",
            name="is_featured",
            field=models.BooleanField(
                default=True,
                help_text="Featured bikes are shown on the homepage.",
                null=True,
            ),
        ),
    ]
