# Generated by Django 6.0 on 2026-01-03 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_motorcycle_is_featured"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="motorcycle",
            name="conditions",
        ),
        migrations.DeleteModel(
            name="MotorcycleCondition",
        ),
    ]
