# Generated by Django 6.0 on 2026-01-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_remove_motorcycle_conditions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="motorcycleimage",
            name="image",
            field=models.ImageField(upload_to="motorcycles/additional/"),
        ),
    ]
