# Generated by Django 6.0 on 2026-01-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_alter_motorcycleimage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="motorcycleimage",
            name="order",
            field=models.IntegerField(default=0),
        ),
    ]
