# Generated by Django 6.0 on 2026-01-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_motorcycleimage_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="motorcycle",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
