# Generated by Django 6.0 on 2026-01-05 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_motorcycle_slug"),
    ]

    operations = []
