# Generated by Django 6.0 on 2026-01-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_motorcycle_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="motorcycle",
            name="discount_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Discounted price (if applicable)",
                max_digits=10,
                null=True,
            ),
        ),
    ]
