# Generated by Django 6.0 on 2026-03-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_alter_motorcycle_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="motorcycle",
            name="is_featured",
            field=models.BooleanField(
                default=True, help_text="Featured bikes are shown on the homepage."
            ),
        ),
    ]
