# Generated by Django 6.0 on 2026-03-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_alter_motorcycle_is_featured"),
    ]

    operations = [
        migrations.AlterField(
            model_name="motorcycle",
            name="condition",
            field=models.CharField(
                blank=True,
                choices=[
                    ("new", "New"),
                    ("used", "Used"),
                    ("demo", "Demo"),
                    ("parts", "Parts"),
                ],
                max_length=20,
            ),
        ),
    ]
