# Generated by Django 6.0 on 2026-03-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_alter_motorcycle_condition"),
    ]

    operations = [
        migrations.AddField(
            model_name="motorcycle",
            name="popular",
            field=models.BooleanField(
                default=False,
                help_text="Popular bikes are highlighted in the listing page.",
            ),
        ),
    ]
