# Generated by Django 6.0 on 2026-03-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0011_motorcycle_popular"),
    ]

    operations = [
        migrations.AddField(
            model_name="motorcycle",
            name="vin",
            field=models.CharField(
                blank=True,
                help_text="Vehicle Identification Number",
                max_length=17,
                null=True,
                unique=True,
            ),
        ),
    ]
