# Generated by Django 6.0 on 2026-03-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0012_motorcycle_vin"),
    ]

    operations = [
        migrations.AddField(
            model_name="motorcycle",
            name="daily_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Daily hire rate (AUD). Used first when calculating hire cost.",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="motorcycle",
            name="is_hire",
            field=models.BooleanField(
                default=False, help_text="This motorcycle is available for hire."
            ),
        ),
        migrations.AddField(
            model_name="motorcycle",
            name="monthly_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Monthly hire rate (AUD). Used as monthly_rate / 30 if daily and weekly rates are not set.",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="motorcycle",
            name="weekly_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Weekly hire rate (AUD). Used as daily_rate / 7 if daily_rate is not set.",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="motorcycle",
            name="status",
            field=models.CharField(
                choices=[
                    ("for_sale", "For Sale"),
                    ("available_soon", "Available Soon"),
                    ("sold", "Sold"),
                    ("reserved", "Reserved"),
                    ("on_hire", "On Hire"),
                    ("unavailable", "Unavailable"),
                ],
                default="for_sale",
                help_text="The sales status of the motorcycle.",
                max_length=20,
            ),
        ),
    ]
