# Generated by Django 6.0 on 2026-03-30 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0013_motorcycle_daily_rate_motorcycle_is_hire_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="motorcycle",
            name="status",
            field=models.CharField(
                choices=[
                    ("for_sale", "For Sale"),
                    ("available_soon", "Available Soon"),
                    ("sold", "Sold"),
                    ("reserved", "Reserved"),
                    ("unavailable", "Unavailable"),
                ],
                default="for_sale",
                help_text="The sales status of the motorcycle.",
                max_length=20,
            ),
        ),
    ]
