# Generated by Django 6.0 on 2026-03-31 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0014_alter_motorcycle_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="motorcycle",
            name="monthly_rate",
        ),
        migrations.RemoveField(
            model_name="motorcycle",
            name="weekly_rate",
        ),
        migrations.AlterField(
            model_name="motorcycle",
            name="daily_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Daily hire rate (AUD). Weekly and monthly discounts are applied globally via Hire Settings.",
                max_digits=8,
                null=True,
            ),
        ),
    ]
