# Generated by Django 6.0 on 2026-05-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0016_motorcycle_is_lams_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="motorcycle",
            name="vehicle_type",
            field=models.CharField(
                choices=[("motorcycle", "Motorcycle"), ("scooter", "Scooter")],
                default="motorcycle",
                help_text="Whether this inventory item is a motorcycle or scooter.",
                max_length=20,
            ),
        ),
    ]
