# Generated by Django 6.0 on 2026-07-27 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0018_motorcycle_available_colours"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="motorcycle",
            name="is_featured",
        ),
    ]
