# Generated by Django 6.0 on 2026-07-29 10:22

import django.db.models.deletion
import inventory.models.bike_order
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0019_remove_motorcycle_is_featured"),
    ]

    operations = [
        migrations.CreateModel(
            name="BikeOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_reference",
                    models.CharField(blank=True, max_length=20, unique=True),
                ),
                (
                    "access_token",
                    models.CharField(
                        default=inventory.models.bike_order._generate_access_token,
                        editable=False,
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("selected_colour", models.CharField(blank=True, max_length=100)),
                ("customer_name", models.CharField(max_length=200)),
                ("customer_email", models.EmailField(max_length=254)),
                ("customer_phone", models.CharField(max_length=50)),
                (
                    "deposit_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Deposit Settings amount snapshotted when the order was created.",
                        max_digits=10,
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_payment", "Pending Payment"),
                            ("paid", "Paid"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending_payment",
                        max_length=20,
                    ),
                ),
                ("terms_accepted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "motorcycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bike_orders",
                        to="inventory.motorcycle",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
