# Generated by Django 6.0 on 2026-08-06 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0022_stockalertcampaign_stockalertsubscriber_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockalertcampaignrecipient",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                    ("delivered", "Delivered"),
                    ("bounced", "Bounced"),
                    ("unsubscribed", "Unsubscribed"),
                    ("complained", "Complained"),
                ],
                default="queued",
                max_length=20,
            ),
        ),
    ]
