# Generated by Django 6.0 on 2026-08-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0023_alter_stockalertcampaignrecipient_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="motorcycle",
            name="include_in_stock_alerts",
            field=models.BooleanField(
                default=True,
                help_text="Include this listing in the next scooter stock-alert email when eligible.",
            ),
        ),
    ]
