# Generated by Django 6.0 on 2026-08-06

from django.db import migrations


def migrate_historic_stock_alert_data(apps, schema_editor):
    Message = apps.get_model('notifications', 'Message')
    Motorcycle = apps.get_model('inventory', 'Motorcycle')
    CampaignItem = apps.get_model('inventory', 'StockAlertCampaignItem')
    Recipient = apps.get_model('inventory', 'StockAlertCampaignRecipient')

    # Old sends did not clear the field. Preserve the new field-only queue
    # semantics: a bike that was in a successfully sent/partially sent update
    # must not be selected again after campaign data is removed.
    sent_bike_ids = CampaignItem.objects.filter(
        campaign__status__in=('sent', 'partial'),
        motorcycle_id__isnull=False,
    ).values_list('motorcycle_id', flat=True)
    Motorcycle.objects.filter(pk__in=sent_bike_ids).update(include_in_stock_alerts=False)

    for recipient in Recipient.objects.exclude(message_id__isnull=True).exclude(subscriber_id__isnull=True):
        Message.objects.filter(pk=recipient.message_id).update(stock_alert_subscriber_id=recipient.subscriber_id)


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_motorcycle_include_in_stock_alerts'),
        ('notifications', '0012_message_stock_alert_subscriber'),
    ]

    operations = [
        migrations.RunPython(migrate_historic_stock_alert_data, migrations.RunPython.noop),
        migrations.DeleteModel(name='StockAlertCampaignRecipient'),
        migrations.DeleteModel(name='StockAlertCampaignItem'),
        migrations.DeleteModel(name='StockAlertCampaign'),
    ]
