# Generated by Django 6.0 on 2026-08-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_remove_stock_alert_campaign_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorcycle',
            name='include_in_stock_alerts',
            field=models.BooleanField(
                default=True,
                help_text='Include this listing in the next stock-alert email.',
            ),
        ),
    ]
