# Generated by Django 6.0 on 2026-03-27 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0013_motorcycle_daily_rate_motorcycle_is_hire_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HireSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enable_hire",
                    models.BooleanField(
                        default=False,
                        help_text="Enable the hire system on the public site.",
                    ),
                ),
                (
                    "bond_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Flat bond amount charged alongside the hire fee (AUD).",
                        max_digits=10,
                    ),
                ),
                (
                    "advance_min_days",
                    models.IntegerField(
                        default=1,
                        help_text="Minimum number of days in advance a hire booking can start.",
                    ),
                ),
                (
                    "advance_max_days",
                    models.IntegerField(
                        default=90,
                        help_text="Maximum number of days in advance a hire booking can start.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Hire Settings",
                "verbose_name_plural": "Hire Settings",
            },
        ),
        migrations.CreateModel(
            name="HireBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booking_reference",
                    models.CharField(blank=True, max_length=20, unique=True),
                ),
                ("hire_start", models.DateField()),
                ("hire_end", models.DateField()),
                (
                    "effective_daily_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Daily rate snapshotted at booking creation time.",
                        max_digits=10,
                    ),
                ),
                (
                    "total_hire_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total hire charge (effective_daily_rate * number of days).",
                        max_digits=10,
                    ),
                ),
                (
                    "bond_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Bond amount snapshotted from HireSettings at booking creation time.",
                        max_digits=10,
                    ),
                ),
                ("customer_name", models.CharField(max_length=200)),
                ("customer_email", models.EmailField(max_length=254)),
                ("customer_phone", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_payment", "Pending Payment"),
                            ("confirmed", "Confirmed"),
                            ("active", "Active"),
                            ("returned", "Returned"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending_payment",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Internal admin notes."),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "motorcycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hire_bookings",
                        to="inventory.motorcycle",
                    ),
                ),
            ],
        ),
    ]
