# Generated by Django 6.0 on 2026-03-27 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hire", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hiresettings",
            name="enable_hire",
        ),
    ]
