# Generated by Django 6.0 on 2026-03-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hire", "0002_remove_hiresettings_enable_hire"),
    ]

    operations = [
        migrations.AddField(
            model_name="hirebooking",
            name="terms_accepted",
            field=models.BooleanField(
                default=False,
                help_text="Customer accepted hire terms and conditions at booking time.",
            ),
        ),
    ]
