# Generated by Django 6.0 on 2026-03-28 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hire", "0003_hirebooking_terms_accepted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hirebooking",
            name="notes",
        ),
    ]
