# Generated by Django 6.0 on 2026-03-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hire", "0004_remove_notes_from_hirebooking"),
    ]

    operations = [
        migrations.AddField(
            model_name="hirebooking",
            name="is_of_age",
            field=models.BooleanField(
                default=False,
                help_text="Customer confirmed they meet the minimum age requirement at booking time.",
            ),
        ),
        migrations.AddField(
            model_name="hiresettings",
            name="minimum_age",
            field=models.IntegerField(
                default=21,
                help_text="Minimum age required to hire a motorcycle (displayed in the booking form).",
            ),
        ),
    ]
