# Generated by Django 6.0 on 2026-03-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hire", "0005_hirebooking_is_of_age_hiresettings_minimum_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="hiresettings",
            name="booking_gap_days",
            field=models.IntegerField(
                default=1,
                help_text="Number of days required between a bike being returned and going out again (for inspection).",
            ),
        ),
    ]
