# Generated by Django 6.0 on 2026-03-29 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hire", "0007_hireextra_hirebookingextra"),
        ("inventory", "0013_motorcycle_daily_rate_motorcycle_is_hire_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HireBlockedDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_from", models.DateField()),
                ("date_to", models.DateField()),
                ("reason", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "motorcycle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked_hire_dates",
                        to="inventory.motorcycle",
                    ),
                ),
            ],
            options={
                "ordering": ["date_from"],
            },
        ),
    ]
