# Generated by Django 6.0 on 2026-03-31 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hire", "0008_hireblockeddate"),
    ]

    operations = [
        migrations.AddField(
            model_name="hiresettings",
            name="monthly_discount_percent",
            field=models.IntegerField(
                default=25,
                help_text="Percentage discount applied to the daily rate for bookings of 30 or more days.",
            ),
        ),
        migrations.AddField(
            model_name="hiresettings",
            name="weekly_discount_percent",
            field=models.IntegerField(
                default=15,
                help_text="Percentage discount applied to the daily rate for bookings of 7 or more days.",
            ),
        ),
    ]
