# Generated by Django 6.0 on 2026-07-29 11:50

import hire.models.hire_booking
import secrets
from django.db import migrations, models


def populate_access_tokens(apps, schema_editor):
    HireBooking = apps.get_model('hire', 'HireBooking')
    used = set(
        HireBooking.objects.exclude(access_token__isnull=True).values_list(
            'access_token', flat=True
        )
    )
    for booking in HireBooking.objects.filter(access_token__isnull=True).iterator():
        token = secrets.token_urlsafe(32)
        while token in used:
            token = secrets.token_urlsafe(32)
        booking.access_token = token
        booking.save(update_fields=['access_token'])
        used.add(token)


class Migration(migrations.Migration):

    dependencies = [
        ("hire", "0009_hiresettings_monthly_discount_percent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hirebooking",
            name="access_token",
            field=models.CharField(editable=False, max_length=64, null=True),
        ),
        migrations.RunPython(populate_access_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="hirebooking",
            name="access_token",
            field=models.CharField(
                default=hire.models.hire_booking._generate_access_token,
                editable=False,
                max_length=64,
                unique=True,
            ),
        ),
    ]
