# Generated by Django 6.0 on 2026-03-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sentmessage",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("customer_confirmation", "Customer Confirmation"),
                    ("admin_new_order", "Admin New Order"),
                    ("admin_reminder", "Admin Reminder"),
                    ("test_email", "Test Email"),
                ],
                max_length=30,
            ),
        ),
    ]
