# Generated by Django 6.0 on 2026-03-14 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("notifications", "0002_alter_sentmessage_message_type"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SentMessage",
            new_name="Message",
        ),
    ]
