# Generated by Django 6.0 on 2026-03-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_rename_sentmessage_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("customer_confirmation", "Customer Confirmation"),
                    ("admin_new_order", "Admin New Order"),
                    ("admin_reminder", "Admin Reminder"),
                    ("test_email", "Test Email"),
                    ("hire_confirmation", "Hire Confirmation"),
                    ("admin_new_hire", "Admin New Hire Booking"),
                ],
                max_length=30,
            ),
        ),
    ]
