# Generated by Codex on 2026-06-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_alter_message_message_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("customer_confirmation", "Customer Confirmation"),
                    ("admin_new_order", "Admin New Order"),
                    ("admin_reminder", "Admin Reminder"),
                    ("test_email", "Test Email"),
                    ("hire_confirmation", "Hire Confirmation"),
                    ("admin_new_hire", "Admin New Hire Booking"),
                    ("admin_service_booking", "Admin Service Booking"),
                ],
                max_length=30,
            ),
        ),
    ]
