# Generated by Django 6.0 on 2026-07-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0006_alter_message_message_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("customer_confirmation", "Customer Confirmation"),
                    ("admin_new_order", "Admin New Order"),
                    ("admin_reminder", "Admin Reminder"),
                    ("test_email", "Test Email"),
                    ("service_booking_confirmation", "Service Booking Confirmation"),
                    ("hire_confirmation", "Hire Confirmation"),
                    ("admin_new_hire", "Admin New Hire Booking"),
                    ("admin_service_booking", "Admin Service Booking"),
                    ("service_booking_reminder", "Service Booking Reminder"),
                ],
                max_length=30,
            ),
        ),
    ]
