# Generated by Django 6.0 on 2026-08-06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_motorcycle_include_in_stock_alerts'),
        ('notifications', '0011_alter_message_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='stock_alert_subscriber',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='messages',
                to='inventory.stockalertsubscriber',
            ),
        ),
    ]
