# Generated by Django 6.0 on 2026-08-06

from django.db import migrations, models


def clear_stock_alert_generic_links(apps, schema_editor):
    Message = apps.get_model('notifications', 'Message')
    Message.objects.filter(message_type='stock_alert_update').update(content_type_id=None, object_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_alter_motorcycle_stock_alert_help_text'),
        ('notifications', '0013_alter_message_stock_alert_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='provider_message_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.RunPython(clear_stock_alert_generic_links, migrations.RunPython.noop),
    ]
