# Generated by Django 6.0 on 2026-08-06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0014_message_provider_id_and_clear_stock_generic_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='provider_message_id',
        ),
    ]
