# Generated by Django 6.0 on 2026-08-08 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0016_alter_message_message_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("customer_confirmation", "Customer Confirmation"),
                    ("admin_new_order", "Admin New Order"),
                    ("admin_reminder", "Admin Reminder"),
                    ("test_email", "Test Email"),
                    ("service_booking_confirmation", "Service Booking Confirmation"),
                    ("hire_confirmation", "Hire Confirmation"),
                    ("admin_new_hire", "Admin New Hire Booking"),
                    ("admin_service_booking", "Admin Service Booking"),
                    ("service_booking_reminder", "Service Booking Reminder"),
                    ("parts_customer_confirmation", "Parts Customer Confirmation"),
                    ("parts_admin_new_order", "Parts Admin New Order"),
                    ("parts_wholesaler_dispatch", "Parts Wholesaler Dispatch"),
                    (
                        "parts_customer_backorder_update",
                        "Parts Customer Backorder Update",
                    ),
                    ("parts_customer_refund_update", "Parts Customer Refund Update"),
                    ("parts_customer_order_arranged", "Parts Customer Order Arranged"),
                    ("stock_alert_update", "Stock Alert Update"),
                    ("bike_interest_reply", "Bike Interest Reply"),
                    ("bike_interest_admin_new", "Bike Interest Admin New Enquiry"),
                ],
                max_length=40,
            ),
        ),
    ]
